from __future__ import annotations

from utils.models import Finding


RULES = {
    "s3_public_bucket": {
        "cis_control_id": "2.1.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-4", "PR.DS-1"],
        "owasp_category": "A01:2021-Broken Access Control",
        "severity": "High",
        "risk_score": 90,
        "recommendation": "Enable S3 Block Public Access and tighten bucket policies.",
        "remediation_steps": [
            "Open the S3 console.",
            "Select the affected bucket.",
            "Enable Block Public Access and review the bucket policy.",
        ],
    },
    "s3_encryption_disabled": {
        "cis_control_id": "2.1.2",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-1"],
        "owasp_category": "A02:2021-Cryptographic Failures",
        "severity": "High",
        "risk_score": 80,
        "recommendation": "Enable default encryption using SSE-S3 or SSE-KMS.",
        "remediation_steps": [
            "Open the S3 console.",
            "Edit bucket default encryption settings.",
            "Enable SSE-S3 or SSE-KMS.",
        ],
    },
    "s3_versioning_disabled": {
        "cis_control_id": "2.1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.IP-4", "RC.RP-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 55,
        "recommendation": "Enable versioning to support recovery and retention use cases.",
        "remediation_steps": [
            "Open the S3 console.",
            "Select the bucket.",
            "Enable bucket versioning.",
        ],
    },
    "s3_public_policy": {
        "cis_control_id": "2.1.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-4", "PR.DS-1"],
        "owasp_category": "A01:2021-Broken Access Control",
        "severity": "Critical",
        "risk_score": 95,
        "recommendation": "Remove public principals from bucket policy and scope access to approved identities only.",
        "remediation_steps": [
            "Open the S3 bucket policy editor.",
            "Find statements with Principal set to '*' or broad external accounts.",
            "Restrict principals and add explicit conditions for least privilege.",
        ],
    },
    "s3_public_acl": {
        "cis_control_id": "2.1.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-4", "PR.DS-1"],
        "owasp_category": "A01:2021-Broken Access Control",
        "severity": "Critical",
        "risk_score": 95,
        "recommendation": "Remove public ACL grants and rely on bucket policies plus block public access controls.",
        "remediation_steps": [
            "Open bucket permissions.",
            "Remove ACL grants for AllUsers and AuthenticatedUsers.",
            "Verify Block Public Access is enabled.",
        ],
    },
    "s3_object_acl_enabled": {
        "cis_control_id": "2.1.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "High",
        "risk_score": 82,
        "recommendation": "Set Object Ownership to Bucket owner enforced to disable ACLs.",
        "remediation_steps": [
            "Open bucket ownership settings.",
            "Set Object Ownership to Bucket owner enforced.",
            "Confirm ACL editing is disabled for objects.",
        ],
    },
    "s3_kms_not_enforced": {
        "cis_control_id": "2.1.2",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-1", "PR.AC-1"],
        "owasp_category": "A02:2021-Cryptographic Failures",
        "severity": "Medium",
        "risk_score": 68,
        "recommendation": "Enforce SSE-KMS as the default bucket encryption standard.",
        "remediation_steps": [
            "Open bucket default encryption settings.",
            "Select AWS KMS key-based encryption (SSE-KMS).",
            "Validate key policy access for required principals.",
        ],
    },
    "s3_tls_not_enforced": {
        "cis_control_id": "2.1.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-2"],
        "owasp_category": "A02:2021-Cryptographic Failures",
        "severity": "High",
        "risk_score": 85,
        "recommendation": "Add a bucket policy deny statement for requests where aws:SecureTransport is false.",
        "remediation_steps": [
            "Open bucket policy editor.",
            "Add Deny for all S3 actions when aws:SecureTransport equals false.",
            "Retest access from HTTPS and HTTP clients.",
        ],
    },
    "s3_mfa_delete_disabled": {
        "cis_control_id": "2.1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-7", "PR.IP-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 62,
        "recommendation": "Enable MFA Delete on versioned buckets that store sensitive or business-critical data.",
        "remediation_steps": [
            "Use AWS CLI with root account credentials for bucket versioning settings.",
            "Enable MFA Delete for the bucket.",
            "Document operational process for MFA-protected deletes.",
        ],
    },
    "s3_access_logging_disabled": {
        "cis_control_id": "3.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["DE.CM-7", "DE.AE-3"],
        "owasp_category": "A09:2021-Security Logging and Monitoring Failures",
        "severity": "Medium",
        "risk_score": 60,
        "recommendation": "Enable S3 server access logging to a dedicated log bucket.",
        "remediation_steps": [
            "Create or select a centralized logging bucket.",
            "Enable server access logging on the source bucket.",
            "Verify logs are being delivered successfully.",
        ],
    },
    "s3_lifecycle_missing": {
        "cis_control_id": "2.1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.IP-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Low",
        "risk_score": 35,
        "recommendation": "Define lifecycle rules for retention and noncurrent object cleanup.",
        "remediation_steps": [
            "Open bucket lifecycle configuration.",
            "Add retention and transition rules for current and previous versions.",
            "Validate lifecycle rule scope against data policy.",
        ],
    },
    "s3_replication_disabled": {
        "cis_control_id": "2.1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["RC.RP-1", "PR.IP-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 58,
        "recommendation": "Enable S3 replication for buckets requiring disaster recovery or cross-region resilience.",
        "remediation_steps": [
            "Create destination bucket and IAM replication role.",
            "Configure replication rules on source bucket.",
            "Validate replicated objects and monitoring alerts.",
        ],
    },
    "s3_required_tags_missing": {
        "cis_control_id": "1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["ID.AM-1", "GV.RR-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Low",
        "risk_score": 32,
        "recommendation": "Apply required ownership and data-classification tags to every production bucket.",
        "remediation_steps": [
            "Define required S3 tag policy (owner, data_classification).",
            "Apply missing tags to bucket resources.",
            "Enforce tags with preventive controls where possible.",
        ],
    },
    "s3_object_lock_disabled": {
        "cis_control_id": "2.1.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-1", "RC.RP-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 64,
        "recommendation": "Enable Object Lock for buckets that require immutable retention.",
        "remediation_steps": [
            "Create a new Object Lock-enabled bucket if current bucket was not created with Object Lock.",
            "Configure retention mode (governance or compliance) and retention period.",
            "Validate legal hold and retention operations.",
        ],
    },
    "iam_wildcard_policy": {
        "cis_control_id": "1.16",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-4"],
        "owasp_category": "A01:2021-Broken Access Control",
        "severity": "High",
        "risk_score": 85,
        "recommendation": "Replace wildcard permissions with least-privilege actions and resources.",
        "remediation_steps": [
            "Review the attached IAM policy.",
            "Remove wildcard actions or resources.",
            "Scope permissions to exact actions and ARNs.",
        ],
    },
    "iam_user_without_mfa": {
        "cis_control_id": "1.2",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-7"],
        "owasp_category": "A07:2021-Identification and Authentication Failures",
        "severity": "High",
        "risk_score": 75,
        "recommendation": "Require MFA for all interactive IAM users.",
        "remediation_steps": [
            "Open the IAM console.",
            "Select the user account.",
            "Assign and enforce a virtual or hardware MFA device.",
        ],
    },
    "ec2_public_ip": {
        "cis_control_id": "4.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "DE.CM-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 60,
        "recommendation": "Remove unnecessary public IP assignments and use private networking.",
        "remediation_steps": [
            "Review the EC2 network interface.",
            "Disassociate the public IP if not required.",
            "Route administration through approved secure access paths.",
        ],
    },
    "ec2_public_ssh": {
        "cis_control_id": "4.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.PT-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Critical",
        "risk_score": 98,
        "recommendation": "Remove the public IP or restrict SSH to approved administrative addresses.",
        "remediation_steps": [
            "Open the EC2 instance network details.",
            "Review attached security groups for port 22 access from 0.0.0.0/0.",
            "Remove the public IP or restrict inbound SSH immediately.",
        ],
    },
    "ec2_public_rdp": {
        "cis_control_id": "4.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.PT-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Critical",
        "risk_score": 98,
        "recommendation": "Remove the public IP or restrict RDP to approved administrative addresses.",
        "remediation_steps": [
            "Open the EC2 instance network details.",
            "Review attached security groups for port 3389 access from 0.0.0.0/0.",
            "Remove the public IP or restrict inbound RDP immediately.",
        ],
    },
    "ec2_imdsv2_not_required": {
        "cis_control_id": "4.2",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.PT-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "High",
        "risk_score": 85,
        "recommendation": "Require IMDSv2 tokens for EC2 instances.",
        "remediation_steps": [
            "Open the EC2 instance metadata options.",
            "Set HttpTokens to required.",
            "Validate workloads that read metadata are IMDSv2-compatible.",
        ],
    },
    "ec2_ebs_unencrypted": {
        "cis_control_id": "2.2.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-1"],
        "owasp_category": "A02:2021-Cryptographic Failures",
        "severity": "High",
        "risk_score": 82,
        "recommendation": "Enable EBS encryption for all attached volumes.",
        "remediation_steps": [
            "Create encrypted snapshots from unencrypted volumes.",
            "Restore encrypted volumes from those snapshots.",
            "Reattach encrypted volumes and validate application health.",
        ],
    },
    "ec2_stopped_instance": {
        "cis_control_id": "4.3",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["ID.AM-1", "PR.IP-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Low",
        "risk_score": 35,
        "recommendation": "Review and remove or remediate stale stopped instances.",
        "remediation_steps": [
            "Review ownership and business need for the stopped instance.",
            "Terminate stale instances or bring them back under patching and hardening controls.",
            "Automate lifecycle cleanup for long-stopped assets.",
        ],
    },
    "ec2_missing_iam_role": {
        "cis_control_id": "1.23",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-1", "PR.AC-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Medium",
        "risk_score": 55,
        "recommendation": "Attach a least-privilege IAM instance profile to each EC2 workload.",
        "remediation_steps": [
            "Create or select a least-privilege IAM role for the workload.",
            "Attach the role as an instance profile to the EC2 instance.",
            "Remove long-lived static credentials from application hosts.",
        ],
    },
    "security_group_open_ssh": {
        "cis_control_id": "4.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.PT-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Critical",
        "risk_score": 95,
        "recommendation": "Restrict SSH access to approved IP addresses or a secure bastion.",
        "remediation_steps": [
            "Open the EC2 security groups console.",
            "Find inbound rule for port 22.",
            "Replace 0.0.0.0/0 with approved administrative IP ranges.",
        ],
    },
    "security_group_open_rdp": {
        "cis_control_id": "4.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.PT-4"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Critical",
        "risk_score": 95,
        "recommendation": "Restrict RDP access to approved IP addresses or a secure access layer.",
        "remediation_steps": [
            "Open the EC2 security groups console.",
            "Find inbound rule for port 3389.",
            "Replace 0.0.0.0/0 with approved administrative IP ranges.",
        ],
    },
    "rds_public_instance": {
        "cis_control_id": "2.3.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.AC-3", "PR.DS-5"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "High",
        "risk_score": 88,
        "recommendation": "Disable public accessibility and place the database in private subnets.",
        "remediation_steps": [
            "Open the RDS console.",
            "Modify the database instance.",
            "Set Publicly accessible to No and confirm private subnet routing.",
        ],
    },
    "rds_encryption_disabled": {
        "cis_control_id": "2.3.2",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["PR.DS-1"],
        "owasp_category": "A02:2021-Cryptographic Failures",
        "severity": "High",
        "risk_score": 82,
        "recommendation": "Use encrypted RDS instances with AWS KMS-backed storage encryption.",
        "remediation_steps": [
            "Plan a snapshot-based migration to an encrypted instance.",
            "Restore or create a new encrypted database.",
            "Cut over traffic after validation.",
        ],
    },
    "cloudtrail_disabled": {
        "cis_control_id": "3.1",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["DE.CM-7", "DE.AE-3"],
        "owasp_category": "A09:2021-Security Logging and Monitoring Failures",
        "severity": "Critical",
        "risk_score": 92,
        "recommendation": "Enable a multi-region CloudTrail trail with logging turned on.",
        "remediation_steps": [
            "Open the CloudTrail console.",
            "Create or select a trail.",
            "Enable multi-region logging and verify trail status is logging.",
        ],
    },
    "aws_config_disabled": {
        "cis_control_id": "3.5",
        "compliance_standard": "CIS AWS Foundations Benchmark v1.4",
        "nist_csf": ["DE.CM-1", "DE.CM-7"],
        "owasp_category": "A09:2021-Security Logging and Monitoring Failures",
        "severity": "Medium",
        "risk_score": 65,
        "recommendation": "Enable AWS Config recording for supported resources in the demo account.",
        "remediation_steps": [
            "Open the AWS Config console.",
            "Create or update the configuration recorder.",
            "Enable recording and verify a delivery channel is configured.",
        ],
    },
    "onprem_smb_signing_disabled": {
        "cis_control_id": "4.8",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["PR.AC-5", "PR.PT-3"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "High",
        "risk_score": 84,
        "recommendation": "Enforce SMB signing on all on-prem Windows servers.",
        "remediation_steps": [
            "Apply Group Policy to require SMB signing for clients and servers.",
            "Validate policy application on critical hosts.",
            "Rescan to confirm SMB relay exposure is removed.",
        ],
    },
    "onprem_rdp_nla_disabled": {
        "cis_control_id": "6.3",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["PR.AC-7", "PR.PT-4"],
        "owasp_category": "A07:2021-Identification and Authentication Failures",
        "severity": "High",
        "risk_score": 86,
        "recommendation": "Require Network Level Authentication (NLA) for all RDP endpoints.",
        "remediation_steps": [
            "Enable NLA in Windows remote access settings or via Group Policy.",
            "Restrict RDP access paths to approved management networks.",
            "Retest remote logon behavior after hardening.",
        ],
    },
    "onprem_host_firewall_disabled": {
        "cis_control_id": "12.2",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["PR.PT-4", "DE.CM-1"],
        "owasp_category": "A05:2021-Security Misconfiguration",
        "severity": "Critical",
        "risk_score": 92,
        "recommendation": "Enable host-based firewalls and enforce baseline inbound rules.",
        "remediation_steps": [
            "Enable Windows Defender Firewall (or equivalent) on affected hosts.",
            "Apply baseline allow-list policy for required management and app ports.",
            "Block unsolicited inbound traffic by default.",
        ],
    },
    "onprem_admin_password_rotation_missing": {
        "cis_control_id": "5.4",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["PR.AC-1", "PR.AC-6"],
        "owasp_category": "A07:2021-Identification and Authentication Failures",
        "severity": "High",
        "risk_score": 83,
        "recommendation": "Implement local administrator password rotation (for example via Microsoft LAPS).",
        "remediation_steps": [
            "Deploy LAPS (or equivalent) for local administrator credential rotation.",
            "Require unique host-level local admin passwords.",
            "Audit privileged local account usage and stale accounts.",
        ],
    },
    "onprem_unsupported_os": {
        "cis_control_id": "7.7",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["ID.AM-2", "PR.IP-12"],
        "owasp_category": "A06:2021-Vulnerable and Outdated Components",
        "severity": "Critical",
        "risk_score": 96,
        "recommendation": "Migrate unsupported operating systems to supported versions.",
        "remediation_steps": [
            "Identify business owners for unsupported assets.",
            "Plan and execute upgrade or replacement to supported OS baselines.",
            "Isolate legacy systems until migration is completed.",
        ],
    },
    "onprem_patching_overdue": {
        "cis_control_id": "7.3",
        "compliance_standard": "CIS Controls v8 / Nessus Audit",
        "nist_csf": ["PR.IP-12", "DE.CM-8"],
        "owasp_category": "A06:2021-Vulnerable and Outdated Components",
        "severity": "High",
        "risk_score": 88,
        "recommendation": "Apply overdue security patches within the defined remediation SLA.",
        "remediation_steps": [
            "Prioritize internet-exposed and privileged systems first.",
            "Patch and reboot assets through approved maintenance windows.",
            "Rescan to verify missing critical patches are remediated.",
        ],
    },
}


def build_finding(
    *,
    service: str,
    resource_id: str,
    issue: str,
    rule_key: str,
    risk_description: str,
    metadata: dict[str, str | int | bool] | None = None,
) -> Finding:
    rule = RULES[rule_key]
    return Finding(
        service=service,
        resource_id=resource_id,
        issue=issue,
        severity=rule["severity"],
        compliance_standard=rule["compliance_standard"],
        risk_description=risk_description,
        recommendation=rule["recommendation"],
        remediation_steps=rule["remediation_steps"],
        cis_control_id=rule["cis_control_id"],
        nist_csf=rule["nist_csf"],
        owasp_category=rule["owasp_category"],
        risk_score=rule["risk_score"],
        metadata=metadata or {},
    )
